if(DEFAULT_BACKEND STREQUAL "OPENCV_DNN")
    add_compile_definitions(USE_OPENCV_DNN)
elseif (DEFAULT_BACKEND STREQUAL "ONNX_RUNTIME")
    set(ORT_VERSION "1.15.1" CACHE STRING "Onnx runtime version") # modify accordingly
    set(ONNX_RUNTIME_DIR $ENV{HOME}/onnxruntime-linux-x64-gpu-${ORT_VERSION} CACHE PATH "Path to onnxruntime")     
    message(STATUS "Onnx runtime version: ${ORT_VERSION}")
    message(STATUS "Onnx runtime directory: ${ONNX_RUNTIME_DIR}")
    find_package(CUDA)
    if (CUDA_FOUND)
        message(STATUS "Found CUDA")
        set(CUDA_TOOLKIT_ROOT_DIR /usr/local/cuda)
    else ()
        message(WARNING "CUDA not found. GPU support will be disabled.")
    endif()
    add_compile_definitions(USE_ONNX_RUNTIME)
elseif (DEFAULT_BACKEND STREQUAL "LIBTORCH")
    set(Torch_DIR $ENV{HOME}/libtorch/share/cmake/Torch/ CACHE PATH "Path to libtorch")
    find_package(Torch REQUIRED)
    add_compile_definitions(USE_LIBTORCH)
elseif (DEFAULT_BACKEND STREQUAL "TENSORRT")
    set(TRT_VERSION "8.6.1.6" CACHE STRING "Tensorrt version") # modify accordingly
    set(TENSORRT_DIR $ENV{HOME}/TensorRT-${TRT_VERSION}/)
    message(STATUS "TENSORRT_DIR: ${TENSORRT_DIR}")
    find_package(CUDA REQUIRED)
    include(QueryGpu)
    add_compile_definitions(USE_TENSORRT)
elseif (DEFAULT_BACKEND STREQUAL "LIBTENSORFLOW")
    find_package(TensorFlow REQUIRED)
    add_compile_definitions(USE_LIBTENSORFLOW)
elseif (DEFAULT_BACKEND STREQUAL "OPENVINO")
    find_package(OpenVINO REQUIRED)
    add_compile_definitions(USE_OPENVINO)   
endif()